/**
 * @fileoverview gRPC-Web generated client stub for essaid.grpc.tims.v0
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.3
// source: essaid/grpc/tims/v0/tims.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.essaid = {};
proto.essaid.grpc = {};
proto.essaid.grpc.tims = {};
proto.essaid.grpc.tims.v0 = require('./tims_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.essaid.grpc.tims.v0.TimsClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.essaid.grpc.tims.v0.TimsPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.essaid.grpc.tims.v0.PathRequest,
 *   !proto.essaid.grpc.tims.v0.Path>}
 */
const methodDescriptor_Tims_N3CPaths = new grpc.web.MethodDescriptor(
  '/essaid.grpc.tims.v0.Tims/N3CPaths',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.essaid.grpc.tims.v0.PathRequest,
  proto.essaid.grpc.tims.v0.Path,
  /**
   * @param {!proto.essaid.grpc.tims.v0.PathRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.essaid.grpc.tims.v0.Path.deserializeBinary
);


/**
 * @param {!proto.essaid.grpc.tims.v0.PathRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.essaid.grpc.tims.v0.Path>}
 *     The XHR Node Readable Stream
 */
proto.essaid.grpc.tims.v0.TimsClient.prototype.n3CPaths =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/essaid.grpc.tims.v0.Tims/N3CPaths',
      request,
      metadata || {},
      methodDescriptor_Tims_N3CPaths);
};


/**
 * @param {!proto.essaid.grpc.tims.v0.PathRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.essaid.grpc.tims.v0.Path>}
 *     The XHR Node Readable Stream
 */
proto.essaid.grpc.tims.v0.TimsPromiseClient.prototype.n3CPaths =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/essaid.grpc.tims.v0.Tims/N3CPaths',
      request,
      metadata || {},
      methodDescriptor_Tims_N3CPaths);
};


module.exports = proto.essaid.grpc.tims.v0;

