# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: essaid/jg/proto/v1/hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x65ssaid/jg/proto/v1/hello.proto\x12\x12\x65ssaid.jg.proto.v1\" \n\x0cHelloRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2^\n\x0cHelloService\x12N\n\x05Hello\x12 .essaid.jg.proto.v1.HelloRequest\x1a!.essaid.jg.proto.v1.HelloResponse\"\x00\x42\x18\n\x16\x63om.essaid.jg.proto.v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'essaid.jg.proto.v1.hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.essaid.jg.proto.v1'
  _globals['_HELLOREQUEST']._serialized_start=54
  _globals['_HELLOREQUEST']._serialized_end=86
  _globals['_HELLORESPONSE']._serialized_start=88
  _globals['_HELLORESPONSE']._serialized_end=121
  _globals['_HELLOSERVICE']._serialized_start=123
  _globals['_HELLOSERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
