// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: essaid/grpc/tims/v0/tims.proto

package com.essaid.grpc.tims.v0;

public final class TimsMsg {
  private TimsMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConceptOrBuilder extends
      // @@protoc_insertion_point(interface_extends:essaid.grpc.tims.v0.Concept)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    java.lang.String getCode();
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>string label = 2;</code>
     * @return The label.
     */
    java.lang.String getLabel();
    /**
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
        getLabelBytes();
  }
  /**
   * Protobuf type {@code essaid.grpc.tims.v0.Concept}
   */
  public static final class Concept extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:essaid.grpc.tims.v0.Concept)
      ConceptOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Concept.newBuilder() to construct.
    private Concept(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Concept() {
      code_ = "";
      label_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Concept();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Concept_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Concept_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.essaid.grpc.tims.v0.TimsMsg.Concept.class, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object code_ = "";
    /**
     * <code>string code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object label_ = "";
    /**
     * <code>string label = 2;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(label_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(label_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.essaid.grpc.tims.v0.TimsMsg.Concept)) {
        return super.equals(obj);
      }
      com.essaid.grpc.tims.v0.TimsMsg.Concept other = (com.essaid.grpc.tims.v0.TimsMsg.Concept) obj;

      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getLabel()
          .equals(other.getLabel())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Concept parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.essaid.grpc.tims.v0.TimsMsg.Concept prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code essaid.grpc.tims.v0.Concept}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:essaid.grpc.tims.v0.Concept)
        com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Concept_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Concept_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.essaid.grpc.tims.v0.TimsMsg.Concept.class, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder.class);
      }

      // Construct using com.essaid.grpc.tims.v0.TimsMsg.Concept.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        code_ = "";
        label_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Concept_descriptor;
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.Concept getDefaultInstanceForType() {
        return com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance();
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.Concept build() {
        com.essaid.grpc.tims.v0.TimsMsg.Concept result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.Concept buildPartial() {
        com.essaid.grpc.tims.v0.TimsMsg.Concept result = new com.essaid.grpc.tims.v0.TimsMsg.Concept(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.essaid.grpc.tims.v0.TimsMsg.Concept result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.label_ = label_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.essaid.grpc.tims.v0.TimsMsg.Concept) {
          return mergeFrom((com.essaid.grpc.tims.v0.TimsMsg.Concept)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.essaid.grpc.tims.v0.TimsMsg.Concept other) {
        if (other == com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance()) return this;
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                code_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                label_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object code_ = "";
      /**
       * <code>string code = 1;</code>
       * @return The code.
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string code = 1;</code>
       * @return The bytes for code.
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        code_ = getDefaultInstance().getCode();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string code = 1;</code>
       * @param value The bytes for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        code_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>string label = 2;</code>
       * @return The label.
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string label = 2;</code>
       * @return The bytes for label.
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string label = 2;</code>
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        label_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string label = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        label_ = getDefaultInstance().getLabel();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string label = 2;</code>
       * @param value The bytes for label to set.
       * @return This builder for chaining.
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        label_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:essaid.grpc.tims.v0.Concept)
    }

    // @@protoc_insertion_point(class_scope:essaid.grpc.tims.v0.Concept)
    private static final com.essaid.grpc.tims.v0.TimsMsg.Concept DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.essaid.grpc.tims.v0.TimsMsg.Concept();
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Concept getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Concept>
        PARSER = new com.google.protobuf.AbstractParser<Concept>() {
      @java.lang.Override
      public Concept parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Concept> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Concept> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.Concept getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PathRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:essaid.grpc.tims.v0.PathRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
     * @return Whether the from field is set.
     */
    boolean hasFrom();
    /**
     * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
     * @return The from.
     */
    com.essaid.grpc.tims.v0.TimsMsg.Concept getFrom();
    /**
     * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
     */
    com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getFromOrBuilder();

    /**
     * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
     * @return Whether the to field is set.
     */
    boolean hasTo();
    /**
     * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
     * @return The to.
     */
    com.essaid.grpc.tims.v0.TimsMsg.Concept getTo();
    /**
     * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
     */
    com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getToOrBuilder();

    /**
     * <code>int32 count = 3;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <code>int32 level = 4;</code>
     * @return The level.
     */
    int getLevel();
  }
  /**
   * Protobuf type {@code essaid.grpc.tims.v0.PathRequest}
   */
  public static final class PathRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:essaid.grpc.tims.v0.PathRequest)
      PathRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PathRequest.newBuilder() to construct.
    private PathRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PathRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PathRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_PathRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_PathRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.essaid.grpc.tims.v0.TimsMsg.PathRequest.class, com.essaid.grpc.tims.v0.TimsMsg.PathRequest.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private com.essaid.grpc.tims.v0.TimsMsg.Concept from_;
    /**
     * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
     * @return Whether the from field is set.
     */
    @java.lang.Override
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
     * @return The from.
     */
    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.Concept getFrom() {
      return from_ == null ? com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : from_;
    }
    /**
     * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
     */
    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getFromOrBuilder() {
      return from_ == null ? com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private com.essaid.grpc.tims.v0.TimsMsg.Concept to_;
    /**
     * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
     * @return Whether the to field is set.
     */
    @java.lang.Override
    public boolean hasTo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.Concept getTo() {
      return to_ == null ? com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : to_;
    }
    /**
     * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
     */
    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getToOrBuilder() {
      return to_ == null ? com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : to_;
    }

    public static final int COUNT_FIELD_NUMBER = 3;
    private int count_ = 0;
    /**
     * <code>int32 count = 3;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_ = 0;
    /**
     * <code>int32 level = 4;</code>
     * @return The level.
     */
    @java.lang.Override
    public int getLevel() {
      return level_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getFrom());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getTo());
      }
      if (count_ != 0) {
        output.writeInt32(3, count_);
      }
      if (level_ != 0) {
        output.writeInt32(4, level_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFrom());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTo());
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, count_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.essaid.grpc.tims.v0.TimsMsg.PathRequest)) {
        return super.equals(obj);
      }
      com.essaid.grpc.tims.v0.TimsMsg.PathRequest other = (com.essaid.grpc.tims.v0.TimsMsg.PathRequest) obj;

      if (hasFrom() != other.hasFrom()) return false;
      if (hasFrom()) {
        if (!getFrom()
            .equals(other.getFrom())) return false;
      }
      if (hasTo() != other.hasTo()) return false;
      if (hasTo()) {
        if (!getTo()
            .equals(other.getTo())) return false;
      }
      if (getCount()
          != other.getCount()) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + getFrom().hashCode();
      }
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.essaid.grpc.tims.v0.TimsMsg.PathRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code essaid.grpc.tims.v0.PathRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:essaid.grpc.tims.v0.PathRequest)
        com.essaid.grpc.tims.v0.TimsMsg.PathRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_PathRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_PathRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.essaid.grpc.tims.v0.TimsMsg.PathRequest.class, com.essaid.grpc.tims.v0.TimsMsg.PathRequest.Builder.class);
      }

      // Construct using com.essaid.grpc.tims.v0.TimsMsg.PathRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFromFieldBuilder();
          getToFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        from_ = null;
        if (fromBuilder_ != null) {
          fromBuilder_.dispose();
          fromBuilder_ = null;
        }
        to_ = null;
        if (toBuilder_ != null) {
          toBuilder_.dispose();
          toBuilder_ = null;
        }
        count_ = 0;
        level_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_PathRequest_descriptor;
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.PathRequest getDefaultInstanceForType() {
        return com.essaid.grpc.tims.v0.TimsMsg.PathRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.PathRequest build() {
        com.essaid.grpc.tims.v0.TimsMsg.PathRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.PathRequest buildPartial() {
        com.essaid.grpc.tims.v0.TimsMsg.PathRequest result = new com.essaid.grpc.tims.v0.TimsMsg.PathRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.essaid.grpc.tims.v0.TimsMsg.PathRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.from_ = fromBuilder_ == null
              ? from_
              : fromBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.to_ = toBuilder_ == null
              ? to_
              : toBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.count_ = count_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.level_ = level_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.essaid.grpc.tims.v0.TimsMsg.PathRequest) {
          return mergeFrom((com.essaid.grpc.tims.v0.TimsMsg.PathRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.essaid.grpc.tims.v0.TimsMsg.PathRequest other) {
        if (other == com.essaid.grpc.tims.v0.TimsMsg.PathRequest.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          mergeFrom(other.getFrom());
        }
        if (other.hasTo()) {
          mergeTo(other.getTo());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getFromFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getToFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                count_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                level_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.essaid.grpc.tims.v0.TimsMsg.Concept from_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> fromBuilder_;
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       * @return Whether the from field is set.
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       * @return The from.
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept getFrom() {
        if (fromBuilder_ == null) {
          return from_ == null ? com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : from_;
        } else {
          return fromBuilder_.getMessage();
        }
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       */
      public Builder setFrom(com.essaid.grpc.tims.v0.TimsMsg.Concept value) {
        if (fromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          from_ = value;
        } else {
          fromBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       */
      public Builder setFrom(
          com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder builderForValue) {
        if (fromBuilder_ == null) {
          from_ = builderForValue.build();
        } else {
          fromBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       */
      public Builder mergeFrom(com.essaid.grpc.tims.v0.TimsMsg.Concept value) {
        if (fromBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            from_ != null &&
            from_ != com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance()) {
            getFromBuilder().mergeFrom(value);
          } else {
            from_ = value;
          }
        } else {
          fromBuilder_.mergeFrom(value);
        }
        if (from_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = null;
        if (fromBuilder_ != null) {
          fromBuilder_.dispose();
          fromBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder getFromBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFromFieldBuilder().getBuilder();
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getFromOrBuilder() {
        if (fromBuilder_ != null) {
          return fromBuilder_.getMessageOrBuilder();
        } else {
          return from_ == null ?
              com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : from_;
        }
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept from = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> 
          getFromFieldBuilder() {
        if (fromBuilder_ == null) {
          fromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder>(
                  getFrom(),
                  getParentForChildren(),
                  isClean());
          from_ = null;
        }
        return fromBuilder_;
      }

      private com.essaid.grpc.tims.v0.TimsMsg.Concept to_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> toBuilder_;
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       * @return Whether the to field is set.
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       * @return The to.
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept getTo() {
        if (toBuilder_ == null) {
          return to_ == null ? com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : to_;
        } else {
          return toBuilder_.getMessage();
        }
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       */
      public Builder setTo(com.essaid.grpc.tims.v0.TimsMsg.Concept value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          to_ = value;
        } else {
          toBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       */
      public Builder setTo(
          com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder builderForValue) {
        if (toBuilder_ == null) {
          to_ = builderForValue.build();
        } else {
          toBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       */
      public Builder mergeTo(com.essaid.grpc.tims.v0.TimsMsg.Concept value) {
        if (toBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            to_ != null &&
            to_ != com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance()) {
            getToBuilder().mergeFrom(value);
          } else {
            to_ = value;
          }
        } else {
          toBuilder_.mergeFrom(value);
        }
        if (to_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = null;
        if (toBuilder_ != null) {
          toBuilder_.dispose();
          toBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder getToBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getToFieldBuilder().getBuilder();
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getToOrBuilder() {
        if (toBuilder_ != null) {
          return toBuilder_.getMessageOrBuilder();
        } else {
          return to_ == null ?
              com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance() : to_;
        }
      }
      /**
       * <code>.essaid.grpc.tims.v0.Concept to = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> 
          getToFieldBuilder() {
        if (toBuilder_ == null) {
          toBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder>(
                  getTo(),
                  getParentForChildren(),
                  isClean());
          to_ = null;
        }
        return toBuilder_;
      }

      private int count_ ;
      /**
       * <code>int32 count = 3;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 3;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {

        count_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 4;</code>
       * @return The level.
       */
      @java.lang.Override
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 4;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {

        level_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:essaid.grpc.tims.v0.PathRequest)
    }

    // @@protoc_insertion_point(class_scope:essaid.grpc.tims.v0.PathRequest)
    private static final com.essaid.grpc.tims.v0.TimsMsg.PathRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.essaid.grpc.tims.v0.TimsMsg.PathRequest();
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.PathRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PathRequest>
        PARSER = new com.google.protobuf.AbstractParser<PathRequest>() {
      @java.lang.Override
      public PathRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PathRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PathRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.PathRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PathOrBuilder extends
      // @@protoc_insertion_point(interface_extends:essaid.grpc.tims.v0.Path)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    java.util.List<com.essaid.grpc.tims.v0.TimsMsg.Concept> 
        getConceptsList();
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    com.essaid.grpc.tims.v0.TimsMsg.Concept getConcepts(int index);
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    int getConceptsCount();
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    java.util.List<? extends com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> 
        getConceptsOrBuilderList();
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getConceptsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code essaid.grpc.tims.v0.Path}
   */
  public static final class Path extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:essaid.grpc.tims.v0.Path)
      PathOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Path.newBuilder() to construct.
    private Path(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Path() {
      concepts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Path();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Path_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Path_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.essaid.grpc.tims.v0.TimsMsg.Path.class, com.essaid.grpc.tims.v0.TimsMsg.Path.Builder.class);
    }

    public static final int CONCEPTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.essaid.grpc.tims.v0.TimsMsg.Concept> concepts_;
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.essaid.grpc.tims.v0.TimsMsg.Concept> getConceptsList() {
      return concepts_;
    }
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> 
        getConceptsOrBuilderList() {
      return concepts_;
    }
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    @java.lang.Override
    public int getConceptsCount() {
      return concepts_.size();
    }
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.Concept getConcepts(int index) {
      return concepts_.get(index);
    }
    /**
     * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
     */
    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getConceptsOrBuilder(
        int index) {
      return concepts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < concepts_.size(); i++) {
        output.writeMessage(1, concepts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < concepts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, concepts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.essaid.grpc.tims.v0.TimsMsg.Path)) {
        return super.equals(obj);
      }
      com.essaid.grpc.tims.v0.TimsMsg.Path other = (com.essaid.grpc.tims.v0.TimsMsg.Path) obj;

      if (!getConceptsList()
          .equals(other.getConceptsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getConceptsCount() > 0) {
        hash = (37 * hash) + CONCEPTS_FIELD_NUMBER;
        hash = (53 * hash) + getConceptsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.essaid.grpc.tims.v0.TimsMsg.Path parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.essaid.grpc.tims.v0.TimsMsg.Path prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code essaid.grpc.tims.v0.Path}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:essaid.grpc.tims.v0.Path)
        com.essaid.grpc.tims.v0.TimsMsg.PathOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Path_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Path_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.essaid.grpc.tims.v0.TimsMsg.Path.class, com.essaid.grpc.tims.v0.TimsMsg.Path.Builder.class);
      }

      // Construct using com.essaid.grpc.tims.v0.TimsMsg.Path.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (conceptsBuilder_ == null) {
          concepts_ = java.util.Collections.emptyList();
        } else {
          concepts_ = null;
          conceptsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.essaid.grpc.tims.v0.TimsMsg.internal_static_essaid_grpc_tims_v0_Path_descriptor;
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.Path getDefaultInstanceForType() {
        return com.essaid.grpc.tims.v0.TimsMsg.Path.getDefaultInstance();
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.Path build() {
        com.essaid.grpc.tims.v0.TimsMsg.Path result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.essaid.grpc.tims.v0.TimsMsg.Path buildPartial() {
        com.essaid.grpc.tims.v0.TimsMsg.Path result = new com.essaid.grpc.tims.v0.TimsMsg.Path(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.essaid.grpc.tims.v0.TimsMsg.Path result) {
        if (conceptsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            concepts_ = java.util.Collections.unmodifiableList(concepts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.concepts_ = concepts_;
        } else {
          result.concepts_ = conceptsBuilder_.build();
        }
      }

      private void buildPartial0(com.essaid.grpc.tims.v0.TimsMsg.Path result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.essaid.grpc.tims.v0.TimsMsg.Path) {
          return mergeFrom((com.essaid.grpc.tims.v0.TimsMsg.Path)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.essaid.grpc.tims.v0.TimsMsg.Path other) {
        if (other == com.essaid.grpc.tims.v0.TimsMsg.Path.getDefaultInstance()) return this;
        if (conceptsBuilder_ == null) {
          if (!other.concepts_.isEmpty()) {
            if (concepts_.isEmpty()) {
              concepts_ = other.concepts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureConceptsIsMutable();
              concepts_.addAll(other.concepts_);
            }
            onChanged();
          }
        } else {
          if (!other.concepts_.isEmpty()) {
            if (conceptsBuilder_.isEmpty()) {
              conceptsBuilder_.dispose();
              conceptsBuilder_ = null;
              concepts_ = other.concepts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              conceptsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConceptsFieldBuilder() : null;
            } else {
              conceptsBuilder_.addAllMessages(other.concepts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.essaid.grpc.tims.v0.TimsMsg.Concept m =
                    input.readMessage(
                        com.essaid.grpc.tims.v0.TimsMsg.Concept.parser(),
                        extensionRegistry);
                if (conceptsBuilder_ == null) {
                  ensureConceptsIsMutable();
                  concepts_.add(m);
                } else {
                  conceptsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.essaid.grpc.tims.v0.TimsMsg.Concept> concepts_ =
        java.util.Collections.emptyList();
      private void ensureConceptsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          concepts_ = new java.util.ArrayList<com.essaid.grpc.tims.v0.TimsMsg.Concept>(concepts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> conceptsBuilder_;

      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public java.util.List<com.essaid.grpc.tims.v0.TimsMsg.Concept> getConceptsList() {
        if (conceptsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(concepts_);
        } else {
          return conceptsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public int getConceptsCount() {
        if (conceptsBuilder_ == null) {
          return concepts_.size();
        } else {
          return conceptsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept getConcepts(int index) {
        if (conceptsBuilder_ == null) {
          return concepts_.get(index);
        } else {
          return conceptsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder setConcepts(
          int index, com.essaid.grpc.tims.v0.TimsMsg.Concept value) {
        if (conceptsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConceptsIsMutable();
          concepts_.set(index, value);
          onChanged();
        } else {
          conceptsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder setConcepts(
          int index, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder builderForValue) {
        if (conceptsBuilder_ == null) {
          ensureConceptsIsMutable();
          concepts_.set(index, builderForValue.build());
          onChanged();
        } else {
          conceptsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder addConcepts(com.essaid.grpc.tims.v0.TimsMsg.Concept value) {
        if (conceptsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConceptsIsMutable();
          concepts_.add(value);
          onChanged();
        } else {
          conceptsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder addConcepts(
          int index, com.essaid.grpc.tims.v0.TimsMsg.Concept value) {
        if (conceptsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConceptsIsMutable();
          concepts_.add(index, value);
          onChanged();
        } else {
          conceptsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder addConcepts(
          com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder builderForValue) {
        if (conceptsBuilder_ == null) {
          ensureConceptsIsMutable();
          concepts_.add(builderForValue.build());
          onChanged();
        } else {
          conceptsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder addConcepts(
          int index, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder builderForValue) {
        if (conceptsBuilder_ == null) {
          ensureConceptsIsMutable();
          concepts_.add(index, builderForValue.build());
          onChanged();
        } else {
          conceptsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder addAllConcepts(
          java.lang.Iterable<? extends com.essaid.grpc.tims.v0.TimsMsg.Concept> values) {
        if (conceptsBuilder_ == null) {
          ensureConceptsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, concepts_);
          onChanged();
        } else {
          conceptsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder clearConcepts() {
        if (conceptsBuilder_ == null) {
          concepts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          conceptsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public Builder removeConcepts(int index) {
        if (conceptsBuilder_ == null) {
          ensureConceptsIsMutable();
          concepts_.remove(index);
          onChanged();
        } else {
          conceptsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder getConceptsBuilder(
          int index) {
        return getConceptsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder getConceptsOrBuilder(
          int index) {
        if (conceptsBuilder_ == null) {
          return concepts_.get(index);  } else {
          return conceptsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public java.util.List<? extends com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> 
           getConceptsOrBuilderList() {
        if (conceptsBuilder_ != null) {
          return conceptsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(concepts_);
        }
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder addConceptsBuilder() {
        return getConceptsFieldBuilder().addBuilder(
            com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance());
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder addConceptsBuilder(
          int index) {
        return getConceptsFieldBuilder().addBuilder(
            index, com.essaid.grpc.tims.v0.TimsMsg.Concept.getDefaultInstance());
      }
      /**
       * <code>repeated .essaid.grpc.tims.v0.Concept concepts = 1;</code>
       */
      public java.util.List<com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder> 
           getConceptsBuilderList() {
        return getConceptsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder> 
          getConceptsFieldBuilder() {
        if (conceptsBuilder_ == null) {
          conceptsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.essaid.grpc.tims.v0.TimsMsg.Concept, com.essaid.grpc.tims.v0.TimsMsg.Concept.Builder, com.essaid.grpc.tims.v0.TimsMsg.ConceptOrBuilder>(
                  concepts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          concepts_ = null;
        }
        return conceptsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:essaid.grpc.tims.v0.Path)
    }

    // @@protoc_insertion_point(class_scope:essaid.grpc.tims.v0.Path)
    private static final com.essaid.grpc.tims.v0.TimsMsg.Path DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.essaid.grpc.tims.v0.TimsMsg.Path();
    }

    public static com.essaid.grpc.tims.v0.TimsMsg.Path getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Path>
        PARSER = new com.google.protobuf.AbstractParser<Path>() {
      @java.lang.Override
      public Path parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Path> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Path> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.essaid.grpc.tims.v0.TimsMsg.Path getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essaid_grpc_tims_v0_Concept_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essaid_grpc_tims_v0_Concept_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essaid_grpc_tims_v0_PathRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essaid_grpc_tims_v0_PathRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_essaid_grpc_tims_v0_Path_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_essaid_grpc_tims_v0_Path_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036essaid/grpc/tims/v0/tims.proto\022\023essaid" +
      ".grpc.tims.v0\"&\n\007Concept\022\014\n\004code\030\001 \001(\t\022\r" +
      "\n\005label\030\002 \001(\t\"\201\001\n\013PathRequest\022*\n\004from\030\001 " +
      "\001(\0132\034.essaid.grpc.tims.v0.Concept\022(\n\002to\030" +
      "\002 \001(\0132\034.essaid.grpc.tims.v0.Concept\022\r\n\005c" +
      "ount\030\003 \001(\005\022\r\n\005level\030\004 \001(\005\"6\n\004Path\022.\n\010con" +
      "cepts\030\001 \003(\0132\034.essaid.grpc.tims.v0.Concep" +
      "t2S\n\004Tims\022K\n\010N3CPaths\022 .essaid.grpc.tims" +
      ".v0.PathRequest\032\031.essaid.grpc.tims.v0.Pa" +
      "th\"\0000\001B\"\n\027com.essaid.grpc.tims.v0B\007TimsM" +
      "sgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_essaid_grpc_tims_v0_Concept_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_essaid_grpc_tims_v0_Concept_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essaid_grpc_tims_v0_Concept_descriptor,
        new java.lang.String[] { "Code", "Label", });
    internal_static_essaid_grpc_tims_v0_PathRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_essaid_grpc_tims_v0_PathRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essaid_grpc_tims_v0_PathRequest_descriptor,
        new java.lang.String[] { "From", "To", "Count", "Level", });
    internal_static_essaid_grpc_tims_v0_Path_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_essaid_grpc_tims_v0_Path_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_essaid_grpc_tims_v0_Path_descriptor,
        new java.lang.String[] { "Concepts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
